# ===================================
# Filter Scope Definitions
# ===================================
scopes:
    active:
        label: 已启用
        type: switch
        default: 2
        conditions:
          - active <> true
          - active = true