plugin:
    name: 培训管理报名系统
    description: 'composer require propaganistas/laravel-phone,composer require maatwebsite/excel,composer require "overtrue/laravel-shopping-cart:~2.0",composer require "jxlwqq/id-validator",composer require intervention/image'
    author: samubra
    icon: oc-icon-coffee
    homepage: ''
navigation:
    training:
        label: 培训管理
        url: samubra/training/setting/index
        icon: icon-archive
    setting:
        label: 基础信息
        url: samubra/training/categories
        icon: icon-life-ring
        sideMenu:
            categories:
                label: 类别管理
                url: samubra/training/categories
                icon: icon-cogs
            organizations:
                label: 发证机构
                url: samubra/training/organizations
                icon: icon-bank
            teachers:
                label: 授课教师
                url: samubra/training/teachers
                icon: icon-user-secret
            courses:
                label: 课程管理
                url: samubra/training/courses
                icon: icon-book
            status:
                label: 状态管理
                url: samubra/training/status
                icon: icon-sort
    plans:
        label: 培训方案
        url: samubra/training/plans
        icon: icon-tint
        sideMenu:
            plans:
                label: 方案管理
                url: samubra/training/plans
                icon: icon-wheelchair
            plancourses:
                label: 授课计划
                url: samubra/training/plancourses
                icon: icon-tree
    projects:
        label: 培训项目
        url: samubra/training/projects
        icon: icon-database
        sideMenu:
            projects:
                label: 项目管理
                url: samubra/training/projects
                icon: icon-truck
            records:
                label: 申请记录
                url: samubra/training/records
                icon: icon-newspaper-o
            projectcourses:
                label: 日程安排
                url: samubra/training/projectcourses
                icon: icon-table
            certificates:
                label: 证书管理
                url: samubra/training/certificates
                icon: icon-suitcase
