plugin:
    name: 培训管理报名系统
    description: 'samubra.training::lang.plugin.description'
    author: samubra
    icon: oc-icon-coffee
    homepage: ''
navigation:
    training:
        label: 培训管理
        url: samubra/training/categories
        icon: icon-life-ring
        sideMenu:
            categories:
                label: 培训类别
                url: samubra/training/categories
                icon: icon-sitemap
            organization:
                label: 发证机构
                url: samubra/training/organizations
                icon: icon-suitcase
            teacher:
                label: 教师管理
                url: samubra/training/teachers
                icon: icon-user-md
