plugin:
    name: 培训管理报名系统
    description: 'samubra.training::lang.plugin.description'
    author: samubra
    icon: oc-icon-coffee
    homepage: ''
navigation:
    training:
        label: 培训管理
        url: samubra/training/setting/index
        icon: icon-archive
        sideMenu:
            setting:
                label: 设置
                url: samubra/training/setting/index
                icon: icon-cog
