scopes:
  is_eligible:
    label: 考试合格
    type: switch
    conditions:
      - is_eligible <> true
      - is_eligible = true
  status:
    label: 受理状态
    modelClass: Samubra\Training\Models\Status
    conditions: record_status_id in (:filtered)
    nameFrom: name
  project:
    label: 培训项目
    modelClass: Samubra\Training\Models\Project
    conditions: project_id in (:filtered)
    nameFrom: title
  certificate:
    label: 培训证书
    modelClass: Samubra\Training\Models\Certificate
    conditions: certificate_id in (:filtered)
    nameFrom: id_num
