title: Certificates
modelClass: Samubra\Training\Models\Certificate
list: $/samubra/training/models/certificate/columns.yaml
recordUrl: 'samubra/training/certificates/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
