name: 培训证书
modelClass: Samubra\Training\Models\Certificate
form: $/samubra/training/models/certificate/fields.yaml
defaultRedirect: samubra/training/certificates
create:
    redirect: 'samubra/training/certificates/update/:id'
    redirectClose: samubra/training/certificates
update:
    redirect: samubra/training/certificates
    redirectClose: samubra/training/certificates
preview: {  }
