list: $/samubra/training/models/course/columns.yaml
modelClass: Samubra\Training\Models\Course
title: 课程列表
filter: config_filter.yaml
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'samubra/training/courses/update/:id'
