title: ProjectCourses
modelClass: Samubra\Training\Models\ProjectCourse
list: $/samubra/training/models/projectcourse/columns.yaml
recordUrl: 'samubra/training/projectcourses/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
