name: ProjectCourses
modelClass: Samubra\Training\Models\ProjectCourse
form: $/samubra/training/models/projectcourse/fields.yaml
defaultRedirect: samubra/training/projectcourses
create:
    redirect: 'samubra/training/projectcourses/update/:id'
    redirectClose: samubra/training/projectcourses
    title: 添加日程安排
    flashSave: 日程安排添加成功！
update:
    redirect: 'samubra/training/projectcourses/update/:id'
    redirectClose: samubra/training/projectcourses
    title: 修改日程安排信息
    flashSave: 日程安排信息修改成功！
    flashDelete: 日程安排已成功删除！
preview:
    title: 查看日程安排详情
