scopes:
  is_retraining:
    label: 复训
    type: checkbox
    conditions: is_retraining = true
  plan_course:
    label: 授课方案
    modelClass: Samubra\Training\Models\PlanCourse
    conditions: plan_course_id in (:filtered)
    nameFrom: course_title
  teacher:
    label: 授课教师
    modelClass: Samubra\Training\Models\Teacher
    conditions: teacher_id in (:filtered)
    nameFrom: name
  project:
    label: 培训项目
    modelClass: Samubra\Training\Models\Project
    conditions: project_id in (:filtered)
    nameFrom: title
  course_time_start:
    label: 授课日期
    type: daterange
    yearRange: 10
    conditions: course_time_start >= ':after' AND course_time_start <= ':before'
  hours:
    label: 学时
    type: numberrange
    conditions: hours >= ':min' and hours <= ':max'