<?php
/**
 * Created by PhpStorm.
 * User: samubra
 * Date: 19-5-25
 * Time: 下午8:37
 */

namespace Samubra\Training\Models\ImportAndExport;


use Samubra\Training\Models\Teacher;
use Samubra\Training\Models\Train;

class ExportTeachers extends \Backend\Models\ExportModel
{
    public function exportData($columns, $sessionKey = null)
    {
        $teachers = Teacher::all();
        $teachers->each(function($teacher) use ($columns) {
            $teacher->edu_type_text = Train::$eduTypeMap[$teacher->edu_type];
            $teacher->job_title_text = Train::$jobTitleMap[$teacher->job_title];
            $teacher->addVisible($columns);
            $teacher->addVisible(['edu_type_text','job_title_text']);
        });
        return $teachers->toArray();
    }

    protected function exportExtendColumns($columns)
    {
        $columns['edu_type_text'] = '文化程度';
        $columns['job_title_text'] = '职称';
        return parent::exportExtendColumns($columns); // TODO: Change the autogenerated stub
    }
}