<?php
/**
 * Created by PhpStorm.
 * User: samubra
 * Date: 19-5-25
 * Time: 下午8:37
 */

namespace Samubra\Training\Models\ImportAndExport;


use Samubra\Training\Models\Course;
use Samubra\Training\Models\Train;
use Samubra\Training\Repositories\Train\TeacherRepository;

class ExportCourses extends \Backend\Models\ExportModel
{
    protected $appends = ['export_type','export_by_course_type','export_by_teacher'];
    protected $fillable = [
        'export_type','export_by_course_type','export_by_teacher'
    ];
    public function exportData($columns, $sessionKey = null)
    {
        $courses = Course::all();
        $courses->each(function($course) use ($columns) {
            if($course->course_type)
                $course->course_type_text = Train::$courseTypeMap[$course->course_type];
            if($course->teacher_id)
                $course->teacher_name = $course->teacher->name;
            $course->addVisible($columns + ['course_type_text','teacher_name']);
        });
        return $courses->toArray();
    }

    protected function exportExtendColumns($columns)
    {
        $columns['course_type_text'] = '课程类型';
        $columns['teacher_name'] = '授课教师';
        return parent::exportExtendColumns($columns); // TODO: Change the autogenerated stub
    }

    public function getExportByCourseTypeOptions()
    {
        return Train::$courseTypeMap;
    }

    public function getExportByTeacherOptions()
    {
        $teacherModel = new TeacherRepository();
        return $teacherModel->all()->pluck('name','id')->toArray();
    }
}