name: Status
modelClass: Samubra\Training\Models\Status
form: $/samubra/training/models/status/fields.yaml
defaultRedirect: samubra/training/status
create:
    redirect: 'samubra/training/status/update/:id'
    redirectClose: samubra/training/status
    title: 添加状态
    flashSave: 状态添加成功！
update:
    redirect: 'samubra/training/status/update/:id'
    redirectClose: samubra/training/status
    title: 修改状态信息
    flashSave: 状态修改成功！
    flashDelete: 状态已成功删除！
preview:
    title: 查看状态详情
