# ===================================
#  Import/Export Behavior Config
# ===================================
import:
  title: 导入授课教师
  modelClass: Samubra\Training\Models\ImportAndExport\ImportTeachers
  list: $/samubra/training/models/teacher/import_columns.yaml

export:
  title: 导出授课教师
  modelClass: Samubra\Training\Models\ImportAndExport\ExportTeachers
  list: $/samubra/training/models/teacher/export_columns.yaml
  fileName: 授课教师列表.csv