list: $/samubra/training/models/teacher/columns.yaml
modelClass: Samubra\Training\Models\Teacher
title: Teachers
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'samubra/training/teachers/update/:id'
