title: 授课计划
modelClass: Samubra\Training\Models\PlanCourse
filter: config_filter.yaml
list: $/samubra/training/models/plancourse/columns.yaml
recordUrl: 'samubra/training/plancourses/preview/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
