title: Plans
modelClass: Samubra\Training\Models\Plan
list: $/samubra/training/models/plan/columns.yaml
recordUrl: 'samubra/training/plans/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
