scopes:
  is_retraining:
    label: 复训
    type: checkbox
    conditions: is_retraining = true
  category:
    label: 培训类别
    modelClass: Samubra\Training\Models\Category
    conditions: category_id in (:filtered)
    nameFrom: name
  is_certificate:
    label: 不发证
    type: checkbox
    conditions: is_certificate <> true
  organization:
    label: 发证机构
    modelClass: Samubra\Training\Models\Organization
    conditions: organization_id in (:filtered)
    nameFrom: name