status_change:
  label: 状态
  view:
    list: $/samubra/training/models/status/relate_columns.yaml
    toolbarButtons: create|add|remove
  manage:
    form: $/samubra/training/models/status/fields.yaml
    recordsPerPage: 10
    scope: project
posts:
  label: 文章
  view:
    list: $/rainlab/blog/models/post/columns.yaml
    toolbarButtons: add|remove
  manage:
    recordsPerPage: 10
    scope: isPublished
