title: 培训项目列表
modelClass: Samubra\Training\Models\Project
filter: config_filter.yaml
list: $/samubra/training/models/project/columns.yaml
recordUrl: 'samubra/training/projects/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
